import { useState } from 'react';
import JSZip from 'jszip/lib/index.js';
import { Download, PackageOpen } from 'lucide-react';
import { icons, type Profile, profileValue } from '@/data/icons';
import { defaultDesign, downloadBlob, makeSvg, pngBlob, slug } from '@/lib/icon-export';

const packKeys = ['fecha', 'hora', 'ubicacion', 'informes'];
export function Pack({ profile, onOpenProfiles }: { profile: Profile | null; onOpenProfiles: () => void }) {
  const [size, setSize] = useState(1024);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');
  const designFor = (key: string) => defaultDesign(icons.find(i => i.key === key)?.name || key, profileValue(key, profile));
  const fileName = (key: string) => `fgdll-${slug(profile?.zone || profile?.name || 'demo')}-${key}.png`;
  async function one(key: string) { setBusy(true); setMessage(''); try { downloadBlob(await pngBlob(key, designFor(key), size, false), fileName(key)); setMessage('PNG descargado.'); } catch (e) { setMessage(e instanceof Error ? e.message : 'No se pudo descargar.'); } finally { setBusy(false); } }
  async function all() { setBusy(true); setMessage('Preparando cuatro imágenes...'); try { const zip = new JSZip(); for (const key of packKeys) zip.file(fileName(key), await pngBlob(key, designFor(key), size, false)); downloadBlob(await zip.generateAsync({ type: 'blob' }), `fgdll-${slug(profile?.zone || profile?.name || 'demo')}-pack.zip`); setMessage('Pack ZIP descargado.'); } catch (e) { setMessage(e instanceof Error ? e.message : 'No se pudo crear el ZIP.'); } finally { setBusy(false); } }
  return <section className="pack-section" id="pack"><div className="pack-head"><div><span className="eyebrow">KIT ESENCIAL / 03</span><h2>Pack del grupo<span className="gold-dot">.</span></h2><p>Cuatro piezas esenciales, listas para comunicar tu próximo encuentro.</p></div><PackageOpen size={38} strokeWidth={1.2}/></div>{!profile && <div className="demo-notice">Estás viendo datos de ejemplo. <button onClick={onOpenProfiles}>Configura tu grupo →</button></div>}<div className="pack-grid">{packKeys.map((key, index) => { const entry = icons.find(i => i.key === key)!; const preview = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(makeSvg(key, designFor(key)))}`; return <article key={key} className="pack-item"><div className="pack-item-preview"><img src={preview} alt={`Vista previa de ${entry.name}`}/></div><div className="pack-item-foot"><div><span>0{index + 1} / {entry.name.toUpperCase()}</span><strong>{profileValue(key, profile)}</strong></div><button disabled={busy} onClick={() => one(key)} aria-label={`Descargar ${entry.name}`}><Download size={19}/></button></div></article>; })}</div><div className="pack-download"><div><strong>Tu pack, en un solo archivo.</strong><span>4 PNG individuales con fondo transparente</span></div><div className="pack-download-actions"><div className="choice-grid two">{[1024,2048].map(n => <button key={n} className={size === n ? 'selected' : ''} onClick={() => setSize(n)}>{n} px</button>)}</div><button className="primary-btn" disabled={busy} onClick={all}><Download size={18}/>{busy ? 'Preparando...' : 'Descargar pack'}</button></div></div>{message && <p className="status-message" role="status">{message}</p>}
  <div className="flyer-section"><div className="flyer-copy"><span className="eyebrow">EN CONTEXTO / 04</span><h3>Así se ve<br/>en un flyer<span className="gold-dot">.</span></h3><p>Una referencia visual de cómo los iconos acompañan la información de tu grupo. Esta vista no se exporta.</p><span className="demo-tag">{profile ? `PERFIL: ${profile.name}` : 'VISTA DEMO · DATOS DE EJEMPLO'}</span></div><div className="flyer"><div className="flyer-top"><span>FRATERNIDAD</span><span>FGDLL / COMUNIDAD</span></div><div className="flyer-center"><span>GUERREROS<br/>DE LA LUZ</span><i></i><strong>{profile?.name || 'Un espacio para encontrarnos'}</strong><small>{profile?.shortText || 'Caminamos juntos hacia la luz.'}</small></div><div className="flyer-bottom">{packKeys.map(key => { const EntryIcon = icons.find(i => i.key === key)!.Icon; return <div key={key}><EntryIcon size={18} strokeWidth={1.6}/><span>{profileValue(key, profile)}</span></div>; })}</div></div></div></section>;
}
