import { useState } from 'react';
import { Check, Copy, Plus, Save, Trash2 } from 'lucide-react';
import { blankProfile, type Profile } from '@/data/icons';

const fields: { key: keyof Profile; label: string; placeholder: string }[] = [
  { key: 'name', label: 'Nombre del grupo', placeholder: 'Ej. Guerreros de la Luz' }, { key: 'zone', label: 'Zona', placeholder: 'Ej. Zona Jaguar' },
  { key: 'center', label: 'Centro', placeholder: 'Ej. Centro FGDLL Norte' }, { key: 'city', label: 'Ciudad o localidad', placeholder: 'Ej. Guadalajara' }, { key: 'address', label: 'Dirección / punto de reunión', placeholder: 'Calle y número' },
  { key: 'days', label: 'Día o días', placeholder: 'Ej. Todos los sábados' }, { key: 'time', label: 'Hora', placeholder: 'Ej. 18:00 h' },
  { key: 'whatsapp', label: 'WhatsApp / informes', placeholder: 'Ej. +52 33 0000 0000' }, { key: 'motto', label: 'Lema', placeholder: 'Una frase para tu grupo' },
  { key: 'colors', label: 'Colores preferidos', placeholder: 'Ej. dorado, azul noche' }, { key: 'notes', label: 'Notas', placeholder: 'Indicaciones internas' }, { key: 'shortText', label: 'Texto corto opcional', placeholder: 'Texto breve para iconos' },
];
export function Profiles({ profiles, activeId, onSave, onDelete, onActivate, onClose }: { profiles: Profile[]; activeId: string | null; onSave: (p: Profile) => void; onDelete: (id: string) => void; onActivate: (id: string) => void; onClose: () => void }) {
  const [draft, setDraft] = useState<Profile>(() => ({ ...blankProfile(), ...(profiles.find(p => p.id === activeId) || {}) }));
  const [error, setError] = useState('');
  function save() { if (!draft.name.trim()) { setError('Escribe el nombre del grupo para guardarlo.'); return; } onSave({ ...draft, name: draft.name.trim() }); setError(''); }
  return <div className="workspace-wrap"><div className="workspace-intro"><span className="eyebrow">CONFIGURACIÓN / 02</span><h2>Mi grupo<span className="gold-dot">.</span></h2><p>Guarda los datos de cada grupo en este navegador. El perfil activo alimenta automáticamente el pack y la vista previa.</p></div>
  <div className="profile-layout"><aside className="profile-list"><div className="panel-heading"><h3>Perfiles guardados</h3><button className="icon-action" onClick={() => { setDraft(blankProfile()); setError(''); }} aria-label="Nuevo perfil"><Plus size={21}/></button></div>{profiles.length ? profiles.map(p => <button className={`profile-row ${p.id === draft.id ? 'selected' : ''}`} key={p.id} onClick={() => { setDraft({ ...blankProfile(), ...p }); setError(''); }}><span className="profile-initial">{p.name.charAt(0).toUpperCase()}</span><span><strong>{p.name}</strong><small>{p.center || p.zone || 'Sin centro'} {p.id === activeId ? '· Activo' : ''}</small></span>{p.id === activeId && <Check size={17} className="gold-text"/>}</button>) : <p className="muted-note">Todavía no hay perfiles. Crea el primero aquí.</p>}</aside>
  <div className="form-panel"><div className="panel-heading"><div><span className="eyebrow">DATOS DEL GRUPO</span><h3>{profiles.some(p => p.id === draft.id) ? 'Editar perfil' : 'Nuevo perfil'}</h3></div></div><div className="form-grid">{fields.map(f => <label className="field" key={f.key}><span>{f.label}</span><input value={draft[f.key]} onChange={e => setDraft({ ...draft, [f.key]: e.target.value })} placeholder={f.placeholder}/></label>)}</div>{error && <p role="alert" className="form-error">{error}</p>}<div className="form-actions"><button className="primary-btn" onClick={save}><Save size={17}/> Guardar perfil</button>{profiles.some(p => p.id === draft.id) && <><button className="secondary-btn" onClick={() => onActivate(draft.id)} disabled={activeId === draft.id}><Check size={17}/>{activeId === draft.id ? 'Perfil activo' : 'Usar este perfil'}</button><button className="secondary-btn" onClick={() => { setDraft({ ...draft, id: crypto.randomUUID(), name: `${draft.name} (copia)` }); setError(''); }}><Copy size={17}/> Duplicar</button><button className="danger-btn" onClick={() => { if (window.confirm('¿Eliminar este perfil?')) { onDelete(draft.id); setDraft(blankProfile()); } }}><Trash2 size={17}/> Eliminar</button></>}</div></div></div><button className="text-link" onClick={onClose}>Volver a la biblioteca →</button></div>;
}
