import { useEffect, useState } from 'react';
import { Heart, Moon, Sun, ArrowUpRight, Shield, Settings2, SlidersHorizontal } from 'lucide-react';
import type { Route } from './+types/home';
import { seo } from '@/lib/seo';
import { Catalog } from '@/components/home/catalog';
import { Profiles } from '@/components/home/profiles';
import { Editor } from '@/components/home/editor';
import { Pack } from '@/components/home/pack';
import { AdminPanel, AdminLogin } from '@/components/home/admin-panel';
import { HelpButton } from '@/components/home/help-button';
import { defaultAdminStore, icons, type AdminStore, type HelpMessage, type Profile } from '@/data/icons';

export function meta({ matches, location }: Route.MetaArgs) { return seo({ matches, location }, { title: 'Sistema de Iconos FGDLL | Iconos para flyers', description: 'Crea, personaliza y descarga iconos institucionales transparentes para los flyers de Fraternidad Guerreros de la Luz.' }); }
export default function HomePage() {
  const [page, setPage] = useState<'home' | 'profiles' | 'editor' | 'admin' | 'favorites'>('home');
  const [selected, setSelected] = useState('fecha');
  const [profiles, setProfiles] = useState<Profile[]>([]);
  const [favorites, setFavorites] = useState<string[]>([]);
  const [adminStore, setAdminStore] = useState<AdminStore>(() => defaultAdminStore());
  const [activeId, setActiveId] = useState<string | null>(null);
  const [light, setLight] = useState(false);
  const [ready, setReady] = useState(false);
  const [adminAuthed, setAdminAuthed] = useState(false);
  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem('fgdll-profiles') || '[]'); if (Array.isArray(saved)) setProfiles(saved); const savedFavorites = JSON.parse(localStorage.getItem('fgdll-favorites') || '[]'); if (Array.isArray(savedFavorites)) setFavorites(savedFavorites); const savedAdmin = JSON.parse(localStorage.getItem('fgdll-admin-store') || 'null'); if (savedAdmin?.sections && savedAdmin?.resources && savedAdmin?.fonts && savedAdmin?.ideas) setAdminStore({ ...defaultAdminStore(), ...savedAdmin }); setActiveId(localStorage.getItem('fgdll-active')); setLight(localStorage.getItem('fgdll-theme') === 'light'); if (sessionStorage.getItem('fgdll-admin-authed') === '1') setAdminAuthed(true); } catch { /* almacenamiento no disponible */ } setReady(true); if ('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(() => { /* instalación no disponible */ }); }, []);
  useEffect(() => { if (!ready) return; try { localStorage.setItem('fgdll-profiles', JSON.stringify(profiles)); localStorage.setItem('fgdll-favorites', JSON.stringify(favorites)); localStorage.setItem('fgdll-admin-store', JSON.stringify(adminStore)); localStorage.setItem('fgdll-active', activeId || ''); localStorage.setItem('fgdll-theme', light ? 'light' : 'dark'); } catch { /* almacenamiento no disponible */ } }, [profiles, favorites, adminStore, activeId, light, ready]);
  const active = profiles.find(p => p.id === activeId) || null;
  function saveProfile(p: Profile) { setProfiles(prev => prev.some(item => item.id === p.id) ? prev.map(item => item.id === p.id ? p : item) : [...prev, p]); if (!activeId) setActiveId(p.id); }
  function deleteProfile(id: string) { setProfiles(prev => prev.filter(p => p.id !== id)); if (activeId === id) setActiveId(null); }
  function toggleFavorite(key: string) { setFavorites(prev => prev.includes(key) ? prev.filter(item => item !== key) : [...prev, key]); }
  function addHelpMessage(message: HelpMessage) { setAdminStore(prev => ({ ...prev, helpMessages: [message, ...prev.helpMessages] })); }
  function navigate(next: typeof page) { setPage(next); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  const favoriteIcons = icons.filter(icon => favorites.includes(icon.key));
  return <div className={`site ${light ? 'light' : ''}`}><header className="site-header"><div className="header-inner"><button className="brand" onClick={() => navigate('home')} aria-label="Ir al inicio"><span className="brand-mark"><Shield size={22} strokeWidth={1.6}/><span>✦</span></span><span><strong>Sistema de Iconos <em>FGDLL</em></strong><small>Iconos y logotipos</small></span></button><div className="header-actions"><span className="header-caption">HERRAMIENTA INSTITUCIONAL</span><button className={`header-profile ${page === 'favorites' ? 'is-current' : ''}`} onClick={() => navigate('favorites')}><Heart size={17}/> Favoritos{favorites.length ? <span className="active-dot"/> : null}</button><button className={`header-profile ${page === 'admin' ? 'is-current' : ''}`} onClick={() => navigate('admin')}><SlidersHorizontal size={17}/> Admin</button><button className={`header-profile ${page === 'profiles' ? 'is-current' : ''}`} onClick={() => navigate('profiles')}><Settings2 size={17}/> Mi grupo{active && <span className="active-dot"/>}</button><button className="theme-button" onClick={() => setLight(!light)} aria-label={light ? 'Activar modo oscuro' : 'Activar modo claro'} title={light ? 'Modo oscuro' : 'Modo claro'}>{light ? <Moon size={19}/> : <Sun size={19}/>}</button></div></div></header>
  <main>{page === 'home' ? <><section className="hero"><div className="hero-inner"><div className="hero-copy"><span className="hero-kicker"><span className="kicker-line"/>FRATERNIDAD GUERREROS DE LA LUZ</span><h1>Editor de<br/>iconos y <span>logos.</span></h1><p>Personaliza iconos, logotipos, datos de grupo, sombras, recursos base y exportaciones PNG transparentes listas para tus diseños.</p><button className="hero-link" onClick={() => document.getElementById('catalogo')?.scrollIntoView({ behavior: 'smooth' })}>Abrir editor <ArrowUpRight size={19}/></button></div><div className="hero-art" aria-hidden="true"><div className="art-frame"><span className="art-top">FGDLL&nbsp; / &nbsp;SISTEMA VISUAL</span><div className="art-center"><span className="art-halo halo-one"/><span className="art-halo halo-two"/><span className="art-star">✦</span></div><span className="art-bottom">UN LENGUAJE.<br/>MUCHAS FORMAS DE ILUMINAR.</span></div><span className="art-index">ICONOS — LOGOS</span></div></div><div className="hero-footer"><span>DISEÑADO PARA SERVIR</span><span>DESLIZA PARA EXPLORAR ↓</span></div></section><div id="catalogo" className="content-wrap"><Catalog onSelect={key => { setSelected(key); navigate('editor'); }}/><Pack profile={active} onOpenProfiles={() => navigate('profiles')}/></div></> : page === 'profiles' ? <Profiles profiles={profiles} activeId={activeId} onSave={saveProfile} onDelete={deleteProfile} onActivate={setActiveId} onClose={() => navigate('home')}/> : page === 'admin' ? (adminAuthed ? <AdminPanel store={adminStore} onChange={setAdminStore} onClose={() => navigate('home')}/> : <AdminLogin onSuccess={() => { setAdminAuthed(true); try { sessionStorage.setItem('fgdll-admin-authed', '1'); } catch { /* almacenamiento no disponible */ } }} onClose={() => navigate('home')}/>) : page === 'favorites' ? <section className="workspace-wrap favorites-page"><div className="workspace-intro"><span className="eyebrow">FAVORITOS</span><h2>Mis iconos<span className="gold-dot">.</span></h2><p>Accesos guardados para reutilizarlos rapido.</p></div>{favoriteIcons.length ? <div className="icon-grid">{favoriteIcons.map(({ key, name, category, Icon }) => <button key={key} className="icon-tile" onClick={() => { setSelected(key); navigate('editor'); }}><Heart size={17} className="tile-heart" fill="currentColor"/><Icon className="tile-symbol" strokeWidth={1.55}/><span className="tile-bottom"><span><strong>{name}</strong><small>{category}</small></span><ArrowUpRight size={17}/></span></button>)}</div> : <p className="empty-state">Todavia no hay favoritos. Abre un icono y pulsa Guardar favorito.</p>}</section> : <Editor key={selected} iconKey={selected} profile={active} adminStore={adminStore} favorites={favorites} onToggleFavorite={toggleFavorite} onBack={() => navigate('home')}/>}</main>
  <HelpButton groupName={active?.name || ''} onSend={addHelpMessage}/>
  <footer className="site-footer"><div><span className="footer-brand">✦ FGDLL</span><span>Fraternidad Guerreros de la Luz</span></div><span>Hecho para quienes comunican con propósito.</span><span>© {new Date().getFullYear()} · Datos guardados en este navegador.</span></footer></div>;
}
